/*
 * Created / Edited by Marek Gajdoš (gajdosm.sk@gmail.com)
 * Copyright (c) 2026 Marek Gajdoš & Lukáš Balážik
 * All rights reserved.
 *
 * This source code is part of a school project.
 * Redistribution, modification, or use outside the scope
 * of this academic project is not permitted without
 * explicit permission from the author(s).
 */

plugins {
    id 'java'
    id 'application'
}

application {
    mainClass = 'sk.handshake.server.HandShake'
}

group = 'sk.handshake.server'
version = '1.1-ALPHA-DEV'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    implementation("io.javalin:javalin:7.2.3")
    implementation('org.apache.logging.log4j:log4j-core:2.25.4')
    implementation('org.apache.logging.log4j:log4j-slf4j2-impl:2.24.3')
    implementation 'com.fasterxml.jackson.core:jackson-core:2.21.4'
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.15.2'
    implementation 'com.fasterxml.jackson.core:jackson-annotations:2.15.2'
}

test {
    useJUnitPlatform()
}

tasks.withType(JavaExec) {
    systemProperty "log4j.skipJansi", "false"
    // Forces Gradle to preserve ANSI colors in the console output
    jvmArgs = ["-Dterminal.jline=true", "-Dlog4j.skipJansi=false"]
}

jar {
    manifest {
        attributes "Main-Class": 'sk.handshake.server.HandShake'
    }

    from {
        configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
    }

    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}